<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Janani" failures="1" tests="2" name="Test" time="0.113" errors="0" timestamp="2023-09-14T15:17:04 PDT">
  <testcase classname="Verify.TestngCheck" name="checkagain" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Verify.TestngCheck.checkagain(TestngCheck.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkagain -->
  <testcase classname="Verify.TestngCheck" name="testAnnotationCheck" time="0.002"/>
</testsuite> <!-- Test -->
